spring:
    application:
        name: superWorld
#    redis:
#      host: localhost
#      port: 6379
#      database: 0
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3307/qx
        username: root
        password: root

server:
    port: 9000


#flyway:
#  encoding: UTF-8
#  locations: com.ys.scs.db.migration,db.migration
#  baseline-on-migrate: true
#  out-of-order: true
