spring:
    application:
        name: superWorld
#    redis:
#      host: localhost
#      port: 6379
#      database: 0
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3307/qx
        username: root
        password: root
    jpa:
      show-sql: false
      hibernate:
        naming:
          physical-strategy: com.ws.misc.PhysicalNamingStrategyStandardImpl
          implicit-strategy: com.ws.misc.ImplicitNamingStrategyStandardImpl
        ddl-auto: none
      open-in-view: true
      properties.hibernate.format_sql: true
      database-platform: org.hibernate.dialect.MySQL5Dialect

server:
    port: 9000


#flyway:
#  encoding: UTF-8
#  locations: com.ys.scs.db.migration,db.migration
#  baseline-on-migrate: true
#  out-of-order: true
