spring:
    application:
        name: superWorld
#    redis:
#      host: localhost
#      port: 6379
#      database: 0
#    datasource:
#        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost/test

server:
    port: 9000